### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by b0red** [toddrob99/searcharr#22]
Hi.
I keep getting this error;
```
today at 10:10:51 Container started
today at 10:10:45 AttributeError: 'NoneType' object has no attribute 'startswith'
today at 10:11:00 Traceback (most recent call last):
today at 10:11:00   File "/app/searcharr.py", line 1114, in <module>
today at 10:11:00     tgr = Searcharr(settings.tgram_token)
today at 10:11:00   File "/app/searcharr.py", line 85, in __init__
today at 10:11:00     radarr.Radarr(settings.radarr_url, settings.radarr_api_key, args.verbose)
today at 10:11:00   File "/app/radarr.py", line 25, in __init__
today at 10:11:00     if not self.radarr_version.startswith("0."):
today at 10:11:00 AttributeError: 'NoneType' object has no attribute 'startswith'
today at 10:11:01 Container stopped
```
This is my settings.py
```

"""
Searcharr
Sonarr & Radarr Telegram Bot
By Todd Roberts
https://github.com/toddrob99/searcharr
"""

# Searcharr Bot
searcharr_password = ""  # Used to authenticate as a regular user to add series/movies
searcharr_admin_password = ""  # Used to authenticate as admin to manage users

# Telegram
tgram_token = "1851256822:AAGXnJQxxxxxxxxxxxxxxxxxxxxxxUHIvif1dDc"

# Sonarr
sonarr_enabled = True
sonarr_url = "http://192.168.xx.xxx:8989"  # http://192.168.1.110:8989
sonarr_api_key = "a4cee1b5e4ac4343b0d8b8b7190xxx"
sonarr_quality_profile_id = "HD 720p"  # can be name or id value
sonarr_add_monitored = True
sonarr_search_on_add = True
sonarr_tag_with_username = True

# Radarr
radarr_enabled = True
radarr_url = "http://192.168.xx.xxx:7878"  # http://192.168.1.110:7878
radarr_api_key = "5015ce27b9274e1b932734366d5xxxx"
radarr_quality_profile_id = "HD-720p"  # can be name or id value
radarr_add_monitored = True
radarr_search_on_add = True
radarr_tag_with_username = True
```

ANd my docker-config.yml
```
      searcharr:
        container_name: searcharr
        hostname: searcharr
        image: toddrob/searcharr:latest
        restart: unless-stopped
        #network_mode: host
        volumes:
          - ${USERDIR}/searcharr/data:/app/data
          - ${USERDIR}/searcharr/logs:/app/logs
          - ${USERDIR}/searcharr/settings.py:/app/settings.py
        environment:
          - TZ=${TZ}
        ports:              # if running network_mode: host, remove ports (or vice versa)
          - "${SEARCHARR_PORT}:8440"
```
