### ISSUE TITLE
Nothing in /app/data or /app/logs when using docker

### ISSUE THREAD

**Issue by frazzyfin** [toddrob99/searcharr#4]
Nothing is in these mapped drives when I start the container in docker compose.

```
searcharr:
    container_name: searcharr
    image: toddrob/searcharr:latest
    volumes:
      - /opt/searcharr/data:/app/data
      - /opt/searcharr/logs:/app/logs
      - /opt/searcharr/settings.py:/app/settings.py
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/London
    restart: unless-stopped
    network_mode: host
```
